### ISSUE TITLE
Instance template cannot be created with specified disk type

### ISSUE THREAD

**Issue by ivanfitenko** [GoogleCloudPlatform/puppet-google-compute#7]
When an instance template is created with disk_type parameter explicitly set, template creation will fail with the following error: 

> Error: /Stage[main]/Profiles::Google::Gcompute_instance_template/Gcompute_instance_template[orocommerce-test1-app-tmpl]/ensure: change from 'absent' to 'present' failed: Could not set 'present' on ensure: Bad response: {
>  "error": {
>   "errors": [
>    {
>     "domain": "global",
>     "reason": "invalid",
>     "message": "Invalid value for field 'resource.properties.disks[0].initializeParams.diskType': 'https://www.googleapis.com/compute/v1/projects/orocloud-dev-ifitenko/zones/us-central1-f/diskTypes/pd-ssd'. DiskType 'https://www.googleapis.com/compute/v1/projects/orocloud-dev-ifitenko/zones/us-central1-f/diskTypes/pd-ssd' must be a valid resource name (not an url)."
>    }
>   ],
>   "code": 400,
>   "message": "Invalid value for field 'resource.properties.disks[0].initializeParams.diskType': 'https://www.googleapis.com/compute/v1/projects/orocloud-dev-ifitenko/zones/us-central1-f/diskTypes/pd-ssd'. DiskType 'https://www.googleapis.com/compute/v1/projects/orocloud-dev-ifitenko/zones/us-central1-f/diskTypes/pd-ssd' must be a valid resource name (not an url)."
>  }
> }

Using self-links for disk types would work for gcompute instances, but for instance templates, string values should be used. As stated in documentation [1]:

>     isks[].initializeParams.diskType string Specifies the disk type to use to create the instance. If not specified, the default is pd-standard, specified using the full URL. For example:
> 
>     https://www.googleapis.com/compute/v1/projects/project/zones/zone/diskTypes/pd-standard
> 
>     Other values include pd-ssd and local-ssd. If you define this field, you can provide either the full or partial URL. For example, the following are valid values:
> 
>     https://www.googleapis.com/compute/v1/projects/project/zones/zone/diskTypes/diskType
>     projects/project/zones/zone/diskTypes/diskType
>     zones/zone/diskTypes/diskType
> 
>     **Note that for InstanceTemplate, this is the name of the disk type, not URL.**

Here is a pull request with a proposed fix: https://github.com/GoogleCloudPlatform/puppet-google-compute/pull/6

[1] https://cloud.google.com/compute/docs/reference/beta/instanceTemplates

**Comment by nelsonjr** [comment]
Hi Ivan! Thanks for taking the time to investigate and file this issue.

The issue is that the disk_type is _not_ a string. On our modules all external resources are exactly that: external resources! There's a long explanation of why this is not simply a string. The short answer is consistency. Granted that in this case having a string would be simpler, but across all API of all products that would be very confusing.

To make an instance template work you have to define somewhere in your manifest a gcompute_disk_type resource that you plan to use. Something line this:

```puppet
gcompute_disk_type { 'pd-standard':
  zone                 => 'us-central1-a',
  project              => 'google.com:graphite-playground',
  credential           => 'mycred',
}
```
Then in the disk_type property you specify the resource identifier. For simplicity I chose in the example above to use `pd-standard` also as the ID, so it would look like this:

```puppet
gcompute_instance_template { 'instance-template':
  ensure     => present,
  properties => {
    disks              => [
      {
        # Tip: Auto delete will prevent disks from being left behind on
        # deletion.
        auto_delete       => true,
        boot              => true,
        initialize_params => {
          disk_type => 'pd-standard',
        }
      }
    ],
  project    => 'google.com:graphite-playground',
  credential => 'mycred',
}
```
Please reopen this issue if the steps above do not work for you and we'll investigate further.
